comment: false

coverage:
  status:
    project:
      default:
        target: 90%
    patch: off

component_management:
  individual_components:
    - component_id: core
      name: Core
      paths:
        - ^packages/core/.*
    - component_id: sql
      name: SQL
      paths:
        - ^packages/sql/.*
    - component_id: js
      name: Javascript Filter
      paths:
        - ^packages/js/.*
    - component_id: elysia-example
      name: Elysia E2E Example
      paths:
        - ^examples/elysia-sqlite/.*
