// AUTOGENERATED FILE
// This file was generated from grammar.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface FiltronActionDict<T> extends BaseActionDict<T> {
  Query?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  OrExpression?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  AndExpression?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  NotExpression_negation?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  NotExpression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpression_parens?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  PrimaryExpression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FieldExpression_comparison?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  FieldExpression_oneOf?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode) => T;
  FieldExpression_notOneOf?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode) => T;
  FieldExpression_existsQuestion?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode) => T;
  FieldExpression_existsKeyword?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  FieldExpression_booleanField?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FieldExpression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  FieldName?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  oneOfOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  notOneOfOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  ComparisonOp?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Value_dottedIdent?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  Value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  stringLiteral?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  stringChar_nonEscaped?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  stringChar_escaped?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  stringChar?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  numberLiteral_float?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: TerminalNode, arg3: IterationNode) => T;
  numberLiteral_int?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode) => T;
  numberLiteral?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  booleanLiteral?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ident?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  identStart?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  identPart?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  keyword?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  and?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  or?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  not?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  true?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  false?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  exists?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  comment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
}

export interface FiltronSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: FiltronActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: FiltronActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: FiltronActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: FiltronActionDict<T>): this;
}

export interface FiltronGrammar extends Grammar {
  createSemantics(): FiltronSemantics;
  extendSemantics(superSemantics: FiltronSemantics): FiltronSemantics;
}

declare const grammar: FiltronGrammar;
export default grammar;

