name: benchmark

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/benchmarks.yml
      - packages/**
      - package.json
      - bun.lock
  pull_request:
    paths:
      - .github/workflows/benchmarks.yml
      - packages/**
      - package.json
      - bun.lock
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  benchmarks:
    name: run
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version-file: package.json
      - run: bun ci
      - run: bun run build
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          mode: simulation
          run: cd packages/benchmark && bun run bench:cpu
      - uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          mode: memory
          run: cd packages/benchmark && bun run bench:memory
